### ISSUE TITLE
Consolidating communications for Data Management TWG

### ISSUE THREAD

**Issue by darothen** [pangeo-data/pangeo-datastore#6]
Hi all,

@kmpaul, @ktyle, @abrammer and myself thought it would be good to consolidate our comms and organizing process looking at creating cloud-optimized datastores for the community here. We've created a nascent team within the pangeo org (@pangeo-data/cloud-data-twg) to help with this.

This Issue is just to document this decision and give others a chance to weigh in or potentially steer us a different direction if there may be an alternative path to consider. I'll keep the Issue open for 30 days and then close it.

**Comment by darothen** [comment]
Our current record of minutes/notes from meetings can be found publicly on Google Docs, [here](https://docs.google.com/document/d/1roo5PWAHua_HkWQaupAxgqTy4vWBscY0pqsWj9phvdk/edit#).

**Comment by rabernat** [comment]
Activity here seems to have stalled. Should we have another meeting soon?

**Comment by kmpaul** [comment]
We have just recently reconnected via email, but I think we should have another meeting soon.  

Should we set up a standing meeting time for updates?  I can put together a poll for everyone to indicate what times work best for them.

**Comment by ktyle** [comment]
@kmpaul sounds good to me!

**Comment by abrammer** [comment]
Yeah, a small meeting would be good in my opinion to recap the discussions from the 3(?) previous meetings and narrow down on objective and short term goals.  

@rabernat I was digging around in various issues.  Is it too late to move https://github.com/pangeo-data/pangeo/issues/507 over here so it's all in one place.

**Comment by kmpaul** [comment]
@abrammer I think moving that issue over would be great.  Especially in line with our effort to consolidate communications.

**Comment by abrammer** [comment]
Given that this issue is about consolidating communications and that @pangeo-data/cloud-data-twg exists with a discussion board.  Should that be the location for internally discussing / scheduling meeting etc, instead of email or slack (e.g. https://github.com/orgs/pangeo-data/teams/cloud-data-twg/discussions/1) or just keep everything in issues. 

And/ or then continue to use issues in this repo as public discussions with meeting notes posted in respective issues? And probably move the previous notes out of google-drive so they're not attached to a single maintainer.
