### ISSUE TITLE
Policy/Thoughts on Observational/Frequently Updating datasets?

### ISSUE THREAD

**Issue by acannistra** [pangeo-data/pangeo-datastore#72]
I'm converting the NOAA Optimum Interpolation Sea Surface Temperature ([OISST](https://www.ncdc.noaa.gov/oisst)) dataset into a zarr array and storing it on our research group's Google Cloud Storage for use on a global-scale climatology project, via Pangeo/Xarray/Dask tooling. It's a fairly useful dataset, and probably holds some merit for inclusion in the pangeo-datastore project. 

However, more interesting to me is that this is a real-time observational dataset, which updates frequently. Because our use-case of the data involves "real-time" monitoring (e.g. analysis using incoming data as it's published), I've begun to implement a "real-time append" cloud function which updates the zarr array in GCS with new observations. 

This begs the question (the reason for this PR) of whether the pangeo-datastore model could (or should) support observational or constantly-changing datasets. 

It seems that from one point of view nothing has to change (intake catalogs can still point to the zarr locations), but that the constantly-updating nature of the dataset means that there has to be some accompanying code and infrastructure to update the data periodically, in order for it to be useful. 

Has there been much discussion around large observational datasets and the pangeo-datastore?

**Comment by sebastienlanglois** [comment]
Hi @acannistra ,

There is a conversation about it going on (or starting at least...) for the ERA5 dataset which is near real time (about 5 days lag).

> @sebastienlanglois - was just looking at the ERA-5 data you've added to the bucket. Do you plan to add hourly data since 2018, or daily ERA-5 data?
_Originally posted by @dgergel in https://github.com/pangeo-data/pangeo-datastore/issues/49#issuecomment-594377577_

I see a lot of value in having dynamic datasets rather than static ones. My reasoning is that users are drawn to pangeo's catalog because of its simplicity, uniformity and cloud-friendly formats.

If pangeo's datasets are outdated (compared to the original dataset provider), some users won't bother with pangeo's catalog at all or will use both pangeo and original provider's which kind of goes against pangeo's vision of simplicity and uniformity.

As implementing your suggestion goes, I would be thrilled to collaborate in a solution as I would like pangeo's ERA5 dataset to be updated periodically. A concern I had for a while is how do you make sure your cloud function is fault-tolerant and won't corrupt a zarr store's metadata if it crashes while appending data. I would be curious to know if your current solution address this risk?

**Comment by rabernat** [comment]
These are all great ideas. Yes, ideally we would like cloud-based data that are updated frequently in perfect sync with the primary provider, and a pipeline that does this in a robust and fault-tolerant way. But actually building this is a complex undertaking. There is no existing, out-of-the-box solution.

For now, I encourage everyone to experiment with dataset updating and learn as much as we can about the challenges. We are working on an NSF proposal that would provide some support for these sorts of things.

**Comment by sebastienlanglois** [comment]
> For now, I encourage everyone to experiment with dataset updating and learn as much as we can about the challenges.

I agree with that. As much as I would like a solution as quickly as possible, we need a fault-tolerant approach or we would run the risk of corrupting pangeo's datasets which is not acceptable.

I can try to experiment with dataset updating and report any valuable findings.
